apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: c2h1a2k=
  mongo-database: bXlkYXRhYmFzZQ==
  mongo-collection: c29sZGllcl9kZXRhaWxz